### ISSUE TITLE
Channel support

### ISSUE THREAD

**Issue by tpope** [noopkat/vim-twitch-line-sign#1]
If you do decide to pursue channels, the Vim side of this is actually pretty straightforward:

```vim
function! s:Callback(channel, msg) abort
  echo a:msg.nick 'says' a:msg.expression 'on line' a:msg.line
endfunction


function! TwitchChatConnect() abort
  let g:twitch_chat_connection = ch_open('localhost:6969', {
        \ 'mode': 'json',
        \ 'callback': function('s:Callback'),
        \ })
endfunction

function! TwitchChatDisconnect() abort
  if exists('g:twitch_chat_connection')
    call ch_close(g:twitch_chat_connection)
    unlet g:twitch_chat_connection
  endif
endfunction
```

The server side would need to do the following:
- run a TCP server on port 6969 (not HTTP, a raw TCP socket)
- when a connection is established, you can communicate with it by sending JSON over it that looks like `[0, {...}]`, followed by a newline.

This doesn't sound hard but I've never done a raw TCP socket in Node before, no idea if the devil is in the details there.

Alternatively, you can use jobs. This is pretty much exactly the same as channels, but instead of a host and a port, you give it a command to run, and send and receive JSON over stdout. You could use this to write a client that does something more conventional like HTTP polling, or perhaps even connect to Twitch chat directly.

**Comment by noopkat** [comment]
copied this pretty much verbatim thank you

**Comment by tpope** [comment]
That was quick!
